### ISSUE TITLE
Documentation on how to seperate the battery charger

### ISSUE THREAD

**Issue by frederickjh** [PricelessToolkit/MailBoxGuard#13]
Hello, 
I am interested in your project and see that one of the features listed in the READMEmd file is that the battery charger can be separated. 

This would be ideal for my use case at a mailbox service where I get my mail. That way I could have two batteries and charge them at home switching them when the battery in use get low.

However I cannot seem to find any documentation regarding how this work. Plus it looks like the one battery contact is on the back of the charger board.

Sorry if I somehow missed the documentation on this in my search. 
Thanks for your project and help!
Frederick

**Comment by PricelessToolkit** [comment]
Hi, 
This feature is more for those who solder board themselves. instead of soldering the 14500 battery holders you need to solder a small 1s lipo connector, and just cut the board in the middle of the two lines. The battery will not run out quickly, you have plenty of time, it’s better to remove the sensor in the evening, charge it, and put it back in the morning, in my opinion, it’s unlikely that you receive new mail at night.  But if you still want to charge the second battery I added the link for a cheap charger ~$3.

Regards
